steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    id: 'install-deps'

  # Build the frontend
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build-frontend'
    waitFor: ['install-deps']

  # Run tests (optional)
  - name: 'node:20'
    entrypoint: npm
    args: ['test']
    id: 'run-tests'
    waitFor: ['install-deps']
    env:
      - 'CI=true'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy-app'
    waitFor: ['build-frontend', 'run-tests']

  # Upload media files to Cloud Storage (if needed)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '-d', 'public/media/', 'gs://${_BUCKET_NAME}/']
    id: 'upload-media'
    waitFor: ['deploy-app']

# Substitution variables
substitutions:
  _BUCKET_NAME: 'your-portfolio-project-media'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Premium build machine
  diskSizeGb: 100

# Timeout for the entire build
timeout: 1800s  # 30 minutes

# Tags for organization
tags: ['portfolio', 'frontend', 'deployment']
